server:
  port: 8083

# 클라이언트 코드에서 Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jwt:
    secret-key: "ZaOhvbAdBvomPAZmhFgcDBaaDNdDBQgGBpv72m85lxj0CNczYpahT6xa0RjcsOnp"
  data:
    redis:
      host: user-redis
      port: 6379
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cow
    url: jdbc:mysql://user-mysql:3307/user
    password: 'miso0805'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'

  #name: config       # 어플리케이션 이름 -> 외부 파일 이름 (config-local)
  profiles:
    active: dev      # 어플리케이션 환경 설정 -> local, dev
  config:
    import: optional:configserver:http://localhost:8088 # import:optional:configserver사용 -> Spring cloud config server 주소

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

admin-service:
  admin-email: admin123@naver.com
  admin-password: 1234

user-service:
  user-email: user123@naver.com
  user-password: 1234