version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/market-msa/user-service
permissions:
  - object: /home/ec2-user/market-msa/user-service
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: deploy-user.sh
      timeout: 60
      runas: root
