name: Product Service

on:
  push:
    branches: [ "product" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Create application.yml
        run: |
          mkdir -p ./product-service/src/main/resources
          echo "${{ secrets.APPLICATION_PROD }}" | base64 --decode > ./product-service/src/main/resources/application.yml

      - name: Build with Gradle
        run: |
          cd product-service
          ./gradlew build -x test

      - name: Docker build
        run: |
          cd product-service
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/product-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_KEY_PROD }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/product-service:latest
            docker stop $(docker ps -a -q)
            docker run -d --log-driver=syslog -p 8082:8082 ${{ secrets.DOCKER_USERNAME }}/product-service:latest
            docker rm $(docker ps --filter 'status=exited' -a -q)
            docker image prune -a -f
